[package]
name = "city-pop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "city-pop"

[dependencies]
csv = "1.2.1"
serde = { version = "1.0.160", features = ["derive"] }
getopts = "0.*"
